### ISSUE TITLE
特性请求： 增加使用代理服务器的选项

### ISSUE THREAD

**Issue by BobH233** [52funny/pikpakcli#10]
国内网络环境有时下载比较的慢，能否增加使用代理服务器下载的选项 ？

**Comment by 52funny** [comment]
很好的提议，近期我会加入的，谢谢你的建议！

**Comment by 52funny** [comment]
@BobH233  `proxy` 已经加入了，请查看 [proxy 配置](https://github.com/52funny/pikpakcli#%E4%BD%BF%E7%94%A8-proxy)

**Comment by BobH233** [comment]
Thanks
