### ISSUE TITLE
下载失败 Failed: unexpected EOF

### ISSUE THREAD

**Issue by SuperWhw** [52funny/pikpakcli#11]
批量下载文件的时候，有概率会遇到这个错误
ERRO[xx] Download xxx Failed: unexpected EOF

不太清楚是什么原因，以及可不可以加入失败重试呢？感谢！

**Comment by 52funny** [comment]
收到你的反馈，有时间我会测试的。

**Comment by 52funny** [comment]
你可以在下载的时候加入 `-c 1` 参数，每次只下载一个文件，看看还有没有出现这个问题。
