### ISSUE TITLE
希望支持java版

### ISSUE THREAD

**Issue by yuzhi-jiang** [52funny/pikpakcli#16]
老大有没有java版的打算
可以打包成一个依赖或者什么来被引入springboot
最近用[spring-file-storage](https://github.com/1171736840/spring-file-storage)的时候,发现支持挺多，刚好买了pikpak的容量，发现使用webdav速度不理想
老大如有兴趣可以看看，能不能支持

**Comment by 52funny** [comment]
谢谢你的建议，不过目前并没有实现 java 的需求，如果大佬有时间可以试一下。
