### ISSUE TITLE
上传到指定文件夹的参数无效。

### ISSUE THREAD

**Issue by wanlyg** [52funny/pikpakcli#17]
-p -P 在windows 和 linux上测试都是无效的，会直接上传到根目录

**Comment by 52funny** [comment]
我目前手头没有win电脑，等我有时间用个虚拟机来测试一下，谢谢你的反馈！

**Comment by wanlyg** [comment]
> 你好根据我的测试，linux上是完全可以的
> 
> ```shell
> ./pikpakcli upload -p folder file
> ```
> 
> folder 是文件夹名字 file是文件名字

已测试当file是文件的时候-p 参数有效，当file是文件夹的时候，-p和-P参数无效

并且还发现当使用-p参数在windows上传文件或文件夹的时候，会出现多个bug。
1.当使用绝对路径时，举例 `.\pikpakcli.exe upload -p abc C:\Users\xxx\Desktop\9999.txt`，程序会把路径C:\Users\xxx\Desktop\当作文件夹请求pikpak，导致服务器返回"error":"file_name_with_illegal_chars
如图![1688476525(1)](https://github.com/52funny/pikpakcli/assets/36926016/298c75bd-864b-4947-8ddc-d548f5a55007)

2.当使用相对路径上传文件时，举例`.\pikpakcli.exe upload -p abc .\test\9999.txt` ，正常的话会把9999.txt上传到根目录abc文件夹下，实际会在根目录abc文件夹下创建test文件夹，再上传9999.txt到根目录/abc/test文件夹下；

3.当使用相对路径上传文件夹时，举例`.\pikpakcli.exe upload -p abc .\test` ，会直接把本地./test文件夹里的内容上传到pikpak的My Upload文件夹。

可能还有其它情况没有测试到。

**Comment by 52funny** [comment]
暂时更新了，你试试可不可以上传
