### ISSUE TITLE
批量下载有些会出现Failed: unexpected EOF和read: connection timed out错误

### ISSUE THREAD

**Issue by xung** [52funny/pikpakcli#18]
目前只支持下载目录, 下载时, 有些文件会出现Failed: unexpected EOF和read: connection timed out错误.
这时对应的文件就不会再下载了(实际上对应的文件可能已经完成了90%了). 再次下载又会重新下载. 
能否添加重试机制或者支持断点续传? 
谢谢!

**Comment by 52funny** [comment]
谢谢你的反馈，之后有时间我会更新的。

**Comment by 52funny** [comment]
@ookiineko has fixed the problem.
