### ISSUE TITLE
Can't use multilevel path

### ISSUE THREAD

**Issue by xanatos** [52funny/pikpakcli#20]
I wasn't able to use a multilevel path like Folder1/Folder2 in, for example, the ls or the new folder commands.

**Comment by xanatos** [comment]
The error is windows-related, I've fixed it in my fork: https://github.com/52funny/pikpakcli/commit/cd7725c4326185ad88e5c6cbf626c542e55774a2

**Comment by 52funny** [comment]
Thanks for the prompt, can you submit a PR?

**Comment by 52funny** [comment]
Thanks for your help, I have updated it to my code: https://github.com/52funny/pikpakcli/commit/ec409eafac5d5e98f26854e5c4694a7dac55d25b
