### ISSUE TITLE
cli好像仅quota -H生效，其他案例，如目录信息，新建文件夹不生效

### ISSUE THREAD

**Issue by yuzhi-jiang** [52funny/pikpakcli#22]
![image](https://github.com/52funny/pikpakcli/assets/45190043/2b4abdd9-9d3a-40a8-9689-c0941c8ca4a0)
![image](https://github.com/52funny/pikpakcli/assets/45190043/1a44d36b-bfaa-4ba3-a943-5e62cdd09a3a)

**Comment by 52funny** [comment]
感谢提供信息，之后有时间我来看看这个问题。

**Comment by 52funny** [comment]
在我测试来看是可以的

**Comment by 52funny** [comment]
我已经更新了windows上的path错误的问题https://github.com/52funny/pikpakcli/commit/ec409eafac5d5e98f26854e5c4694a7dac55d25b
