### ISSUE TITLE
能不能加一个上传完了一个文件，在命令行显示一下这个文件上传完了

### ISSUE THREAD

**Issue by mortoys** [52funny/pikpakcli#28]
目前上传过程中没有任何提示，必须到客户端查看才知道上传完成了

最好能加个
1. 上传完成了哪个文件
2. 已经上传了几个文件
3. 还有几个文件
4. 上传的平均速度是多少
5. 已经上传了百分之多少
6. 预计还需要多少时间

会让这个小工具更好用，谢谢开发者的无私奉献🙏

**Comment by 52funny** [comment]
好像之前也有这个需求，就是显示上传的信息。但是我喜欢简约风格。
不过这个好像很多人有这个需求，可以考虑加一下！
