### ISSUE TITLE
幸苦啦！能不能优化一下下载显示呢？

### ISSUE THREAD

**Issue by Baidu0Big** [52funny/pikpakcli#29]
感谢作者的作品，请问能否把下载显示优化一下呢🤔。现在长文本会直接省略导致看不见速度与ETA，可能是我终端问题？

**Comment by 52funny** [comment]
好的，我看看。

**Comment by 52funny** [comment]
最新一次的提交 https://github.com/52funny/pikpakcli/commit/d6f24b50560018a3599753fb8e69fd6144bf23df ，
暂时对过长的文本进行了显示部分，但这个不是一个好办法。
可以进行pr！thanks！

**Comment by 52funny** [comment]
你可以先自己编译一个可执行文件看看是不是可以解决文件名过长带来的问题。
