### ISSUE TITLE
是否考虑支持token验证？

### ISSUE THREAD

**Issue by abcfy2** [52funny/pikpakcli#30]
我的账号没有密码，是通过google账号oauth2生成并登录的，是否考虑像 [BaiduPCS-Go](https://github.com/qjfoidnh/BaiduPCS-Go) 那样支持token登录呢？谢谢

**Comment by SingingDalong** [comment]
> abcfy2

If you register your email/password in the [Account and Security] settings on the mypikpak webpage, you can log in with your email/password.
