### ISSUE TITLE
请问下载文件时是否通过根文件夹ID来确定文件夹

### ISSUE THREAD

**Issue by garyvalue** [52funny/pikpakcli#31]
例如这样，如果文件夹有空格，貌似识别不出来
![image](https://github.com/52funny/pikpakcli/assets/38098459/6a96ef35-7c99-4026-b447-9817d6b15ba3)

**Comment by 52funny** [comment]
在终端里面，如果有空格可以用引号包裹起来这样就可以识别空格。
