### ISSUE TITLE
登陆不了,提示login error: captcha_required

### ISSUE THREAD

**Issue by CJN1986** [52funny/pikpakcli#32]
软件版本是[0.17](https://github.com/52funny/pikpakcli/releases/tag/v0.17)
config.yml里配置了邮箱和密码, 在网页版用邮箱密码登陆正常没有captcha验证

```bash
pikpakcli --config config.yml quota -H
ERRO[0000] Login Failed: login error: captcha_required
total               used
0B                  0B
```

**Comment by vizv** [comment]
Having the same issue, maybe https://github.com/Quan666/PikPakAPI/commit/6ada88ba59e2704f0969a9d3c4538c60d49b7c0e could help?

**Comment by lotaku** [comment]
me too

**Comment by SingingDalong** [comment]
I think the new version of alist solved it. Developer! Please update it. And thank you for developing a good Util. Stay healthy!

**Comment by 52funny** [comment]
This issue has been fixed by @vizv .
