### ISSUE TITLE
problem with folder/file.extension syntax

### ISSUE THREAD

**Issue by HongYue1** [52funny/pikpakcli#37]
~I can simply download folders but when trying to download files I get this error:
`ERRO[0002] Get Parent Folder Id Failed: not found pikpak folder`~

![2024-07-15_16-18](https://github.com/user-attachments/assets/33e9004a-c57f-4cda-a0c7-55fc86fe1042)

**Comment by HongYue1** [comment]
Update: this happens only when:
1- file is in root directory
2- if I put the file in another directory and try to download it, this path syntax doesn't work `-p folder/filename.jpg` but these two syntax works fine `-p folder  filename.jpg` and this `-P folder_ID filename.jpg`

**Comment by 52funny** [comment]
I'll finish the documentation later, and thanks for the suggestion. @HongYue1

**Comment by 52funny** [comment]
In the latest commit https://github.com/52funny/pikpakcli/commit/2c443e8b251f9168eeeb5942e4c9c0ec023dd426, I finished revising the docs.

**Comment by HongYue1** [comment]
> In the latest commit [2c443e8](https://github.com/52funny/pikpakcli/commit/2c443e8b251f9168eeeb5942e4c9c0ec023dd426), I finished revising the docs.

Thanks!
