### ISSUE TITLE
pikpakcli not working in the google shell

### ISSUE THREAD

**Issue by moerxiushissss** [52funny/pikpakcli#38]
我在google cloud shell中尝试将大文件上传到pikpak中，前面go编译时都顺利，最后运行时却提示权限不足：
root@cloudshell:~/pikpakcli$ ./pikpakcli
-bash: ./pikpakcli: Permission denied

我已检查，该文件有运行权限

**Comment by 52funny** [comment]
可以提供更多的信息么，这样我能更好的解决问题！

**Comment by 52funny** [comment]
Missing context information
