### ISSUE TITLE
ERRO[0000] Login Failed: login error: invalid_argument

### ISSUE THREAD

**Issue by jchen8tw** [52funny/pikpakcli#39]
I think the error may have occurred because of the new captcha token.
You can also refer to another pikpak related project for the recent update on captcha token.
https://github.com/Quan666/PikPakAPI/commit/649ed09649fea3e13a802adcd95d320d76b8e7a5

Thank you for maintaining this project.

**Comment by 52funny** [comment]
I've fixed it in the latest commit! https://github.com/52funny/pikpakcli/commit/23a5d8aa17144a59fc429a4afae7bff47f976a65
Thank you for your help with this project!
