### ISSUE TITLE
Windows下上传好像就是不会保留目录结构

### ISSUE THREAD

**Issue by m1omoe** [52funny/pikpakcli#7]
命令：
pikpakcli upload -p Movies .

[![pSLCJv6.png](https://s1.ax1x.com/2023/02/18/pSLCJv6.png)](https://imgse.com/i/pSLCJv6)

[![pSLCUbD.png](https://s1.ax1x.com/2023/02/18/pSLCUbD.png)](https://imgse.com/i/pSLCUbD)

**Comment by 52funny** [comment]
已经解决了，随后我将进行打包上传。
