### ISSUE TITLE
能否将下载文件夹时的参数换成文件夹的id

### ISSUE THREAD

**Issue by KiritoGuugk** [52funny/pikpakcli#9]
能否将下载文件夹时的参数换成文件夹的id(pikpak网页版地址栏上的涂掉那一串英文)，这样有一些比较深的文件夹不用一个一个打，直接从浏览器地址栏复制就好了
![image](https://user-images.githubusercontent.com/35999227/224552358-31514e74-6d49-45b8-b4c1-85494c9adfe6.png)

**Comment by 52funny** [comment]
很不错的建议，最近我会加入这个特性。

**Comment by 52funny** [comment]
已完成你的建议，可以使用 `-P` 来指定文件夹的 `id`。可以参考 README 里面的 [上传指令](https://github.com/52funny/pikpakcli#%E4%B8%8A%E4%BC%A0)，下载都是大同小异的。
